$(function(){
    $("#b0").bind({
        "mouseenter":function(){
            $("#a0").css({
                "display":"block"
            })
        },        
        "mouseleave":function(){
            $("#a0").css({
                "display":"none"
            })
        }
    });
    $("#b1").bind({
        "mouseenter":function(){
            $("#a1").css({
                "display":"block"
            })
        },        
        "mouseleave":function(){
            $("#a1").css({
                "display":"none"
            })
        }
    });
    $("#b2").bind({
        "mouseenter":function(){
            $("#a2").css({
                "display":"block"
            })
        },        
        "mouseleave":function(){
            $("#a2").css({
                "display":"none"
            })
        }
    });
    $("#b3").bind({
        "mouseenter":function(){
            $("#a3").css({
                "display":"block"
            })
        },        
        "mouseleave":function(){
            $("#a3").css({
                "display":"none"
            })
        }
    });
    $("#b4").bind({
        "mouseenter":function(){
            $("#a4").css({
                "display":"block"
            })
        },        
        "mouseleave":function(){
            $("#a4").css({
                "display":"none"
            })
        }
    });
    
});